server.port=8083
spring.application.name=generator-service

spring.config.import=optional:configserver:http://localhost:8888

# Priority Settings: Allow local properties to override remote Git config
spring.cloud.config.allow-override=true
spring.cloud.config.override-none=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true