spring.application.name=api-gateway
server.port=8080
spring.config.import=optional:configserver:http://localhost:8888

# Priority Settings: Allow local properties to override remote Git config
spring.cloud.config.allow-override=true
spring.cloud.config.override-none=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# User Service Route
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=CircuitBreaker=name=userServiceCB,fallbackUri=forward:/fallback/user
spring.cloud.gateway.routes[0].filters[1]=RateLimit=10,1

# Vault Service Route
spring.cloud.gateway.routes[1].id=vault-service
spring.cloud.gateway.routes[1].uri=lb://VAULT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/vault/**
spring.cloud.gateway.routes[1].filters[0]=CircuitBreaker=name=vaultServiceCB,fallbackUri=forward:/fallback/vault
spring.cloud.gateway.routes[1].filters[1]=RateLimit=5,1

# Generator Service Route
spring.cloud.gateway.routes[2].id=generator-service
spring.cloud.gateway.routes[2].uri=lb://GENERATOR-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/generator/**
spring.cloud.gateway.routes[2].filters[0]=CircuitBreaker=name=generatorServiceCB,fallbackUri=forward:/fallback/generator
spring.cloud.gateway.routes[2].filters[1]=RateLimit=5,1

# Security Service Route
spring.cloud.gateway.routes[3].id=security-service
spring.cloud.gateway.routes[3].uri=lb://SECURITY-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/security/**
spring.cloud.gateway.routes[3].filters[0]=CircuitBreaker=name=securityServiceCB,fallbackUri=forward:/fallback/security
spring.cloud.gateway.routes[3].filters[1]=RateLimit=5,1

# Notification Service Route
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[4].filters[0]=CircuitBreaker=name=notificationServiceCB,fallbackUri=forward:/fallback/notification
spring.cloud.gateway.routes[4].filters[1]=RateLimit=10,1

# Global CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true