server.port=8888
spring.application.name=config-server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Use native (local) config instead of Git
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configs